package subsystems;

public enum State {
    INIT,

    PREPARE_SAMPLE,
    PICKUP_SAMPLE,
    LEAVE_SAMPLE_BASKET,
    LEAVE_SAMPLE_OBSERVATION,

    PREPARE_TRANSFER,
    DO_TRANSFER,
    DO_TRANSFER2,

    OPEN_CLAW,
    CLOSE_CLAW,
    HOLD_SAMPLE,

    PREPARE_SPECIMEN,
    PICKUP_SPECIMEN,
    PREPARE_LEAVE_SPECIMEN,
    LEAVE_SPECIMEN,
    RAISE_VERTICAL,
    LEAVE_SPECIMEN_RANK,
    LOWER_VERTICAL
}